/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated', // Usa la generación automática
      dirName: '.', // Desde la raíz de la carpeta docs (que ahora solo tiene 'kubernetes')
    },
  ],
};

module.exports = sidebars;
