/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Cluster Kubernetes HA Lab', // Tu etiqueta
      // --- ELIMINA O COMENTA ESTA SECCIÓN DE LINK ---
      // link: {
      //    type: 'generated-index',
      //    title: 'Introducción',
      // },
      // ----------------------------------------------
      items: [
        {
           type: 'autogenerated',
           dirName: 'kubernetes',
        },
      ],
    },
  ],
};

module.exports = sidebars;
